// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BNfOTVcNL0IE3WUkvgsl6puClnVoxgY',
    appId: '1:130311739220:web:57eceaf787396e3bc95ac1',
    messagingSenderId: '130311739220',
    projectId: 'birim-donusturucu-92580',
    authDomain: 'birim-donusturucu-92580.firebaseapp.com',
    storageBucket: 'birim-donusturucu-92580.firebasestorage.app',
    measurementId: 'G-1QJDLTMJ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC999CT8SmAr7Y-_rMdHb5kGAUSbMmyeOk',
    appId: '1:130311739220:android:57f5600c82b6e229c95ac1',
    messagingSenderId: '130311739220',
    projectId: 'birim-donusturucu-92580',
    storageBucket: 'birim-donusturucu-92580.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_BNfOTVcNL0IE3WUkvgsl6puClnVoxgY',
    appId: '1:130311739220:web:92f975bf23dab01ac95ac1',
    messagingSenderId: '130311739220',
    projectId: 'birim-donusturucu-92580',
    authDomain: 'birim-donusturucu-92580.firebaseapp.com',
    storageBucket: 'birim-donusturucu-92580.firebasestorage.app',
    measurementId: 'G-14LHCBGCMS',
  );
}